name: Deploy
on:
  push:
    branches:
      - master
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: LLK/scratch-gui
          ref: v3.6.18
      - run: npm install
      - uses: actions/checkout@v2
        with:
          path: ./posenet2scratch
      - run: sh ./posenet2scratch/install.sh
      - run: npm run build
      - name: npm install under posenet2scratch
        run: npm install
        working-directory: ./posenet2scratch
      - name: Build posenet2scratch.mjs for xcratch
        run: npm run build
        working-directory: ./posenet2scratch
      - name: Copy posenet2scratch.mjs to build folder
        run: cp ./posenet2scratch/dist/posenet2scratch.mjs ./build
      - name: Copy sample.sb3 to build folder
        run: cp ./posenet2scratch/sample_projects/xcratch/sample.sb3 ./build
      - name: Copy kashikokunaru.sb3 to build folder
        run: cp ./posenet2scratch/sample_projects/xcratch/kashikokunaru.sb3 ./build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
